
var test = 
[
     ['HOLA','chinx/1','chinx:oRight=true,box=pj1;function:setActor=zoey+1'],
     ['¿COMO ESTAN?','chinx/2','chinx:oRight=false,box=pj2;control:speed=25,paget=1000'],
     ['Espero que estes muy bien en este bonito dia','chinx/1',''],
     [' ','chinx/1',''],
     [' ','chinx/2','function:ctm=callate+ctm'],
     ['te lo suplicoooooo','chinx/3',''],
     ['RESPONDE PLSsssssssssssssss','chinx/4','function:sleep=on']
];


var historyTest = 
[
     ["Hola","chinx/1",""],
     ["Esto es una prueba","chinx/2",""],
     ["Vamos a probar algunas funciones y ver si todo sale bien","chinx/3",""],
     ["¿Entendido?","chinx/4","control:paget=1500"],
     ["Bien","chinx/3","control:paget=1000"],
     ["Primero vamos a ver la velocidad de habla","chinx/5",""],
     ["Se está mostrando un diálogo en texto en una caja con bordes blancos y fondo oscuro","chinx/6",""],
     ["En la parte de abajo","chinx/5",""],
     ["","chinx/7",""],
     ["","chinx/8",""],
     ["Supuestamente","chinx/5",""],
     ["","chinx/7","control:paget=400"],
     ["","chinx/8",""],
     ["","chinx/9","control:paget=1000"],
     ["","chinx/10","control:paget=1000"],
     ["Bueno no importa","chinx/5",""],
     ["Se probara velocidad de promnium","chinx/6",""],
     ["promium","chinx/11","control:speed=100"],
     ["pronium","chinx/11","control:speed=150,paget=200"],
     ["PROnium","chinx/11","control:speed=100"],
     ["proNUN","chinx/11","control:speed=70"],
     ["proMUNi","chinx/11","control:speed=30"],
     ["primiun","chinx/11","control:speed=70"],
     ["PROmiun","chinx/11",""],
     ["pronium","chinx/11",""],
     ["de PRONUNCIACIÓN","chinx/12","control:speed=50,paget=1000"],
     ["a una velocidad muy rapida","chinx/5",""],
     ["muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy","chinx/6","control:speed=10,paget=10"],
     ["muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy muy ","chinx/6","control:speed=5"],
     ["muy muy muy muy muy muy muy muy muy muy muy pero que muy ...","chinx/5","control:paget=2100"],
     ["R A P I D O","chinx/6","control:speed=100"],
     ["ahora se probará el tiempo de espera","chinx/5","control:speed=50"],
     ["Que es el tiempo de espera?","chinx/17","control:paget=1500"],
     ["","chinx/10","control:paget=1000"],
     ["aquí dice que es el tiempo que se tarda en iniciar la siguiente línea de diálogo","chinx/5","control:paget=1000"],
     ["como está","chinx/13","control:paget=1000"],
     ["y esta","chinx/14","control:paget=750"],
     ["y esta","chinx/15","control:paget=500"],
     ["y esta","chinx/16","control:paget=250"],
     ["y esta","chinx/13","control:paget=100"],
     ["y esta","chinx/14",""],
     ["y esta","chinx/15",""],
     ["y esta","chinx/16",""],
     ["y esta","chinx/13",""],
     ["y por ultima","chinx/17","control:paget=1000"],
     ["esto","chinx/18","control:paget=500"],
     ["Ahora vamos a cambiar de fondo","chinx/12",""],
     ["Como solo es prueba, vamos a cambiar los fondos de prueba","chinx/5",""],
     ["muestren el fondo 2","chinx/19",""],
     ["","chinx/20",""],
     ["","chinx/20","function:bg=1"],
     ["Perfecto","chinx/21",""],
     ["el siguiente, fondo 3","chinx/19",""],
     ["","chinx/20",""],
     ["","chinx/20","function:bg=2"],
     ["Un momento","chinx/20",""],
     ["Ese es el 4, falta el fondo 3","chinx/21",""],
     ["pongan el fondo fondo 3","chinx/19",""],
     ["","chinx/20",""],
     ["","chinx/20","function:bg=3;control:paget=500"],
     ["","chinx/22",""],
     ["REGRESA! REGRESA!","chinx/23","control:paget=1000,speed=50"],
     ["","chinx/24","control:paget=700,"],
     ["","chinx/24","control:paget=800,speed=50;function:bg=0"],
     ["Creo que es suficiente","chinx/25",""],
     ["¿que más sigue?","chinx/26",""],
     ["ah! Ya recordé","chinx/12",""],
     ["aparecer y desaparecer","chinx/5",""],
     ["mira, magia","chinx/13",""],
     ["estoy","chinx/28",""],
     ["y ahora no estoy","chinx/27",""],
     ["BOOOAAAAAAAAAAAAA!","chinx/29",""],
     ["Soy un monstruo","chinx/30",""],
     ["Perdona, no resistí las ganas de hacerlo","chinx/31",""],
     ["Continuemos","chinx/12",""],
     ["Ahora es momento de ver los lados","chinx/5",""],
     ["Ahora estoy en el lado IZQUIERDO de tu pantalla","chinx/32",""],
     ["Debo probar si podré estar en el lado DERECHO","chinx/33",""],
     ["Ahora aquí estoy","chinx/34",""],
     ["y ahora aquí ","chinx/34","chinx:oRight=false,box=pj2"],
     ["Ahora volveré a mi lugar de inicio","chinx/34",""],
     ["Ya","chinx/34","chinx:oRight=true,box=pj1"],
     ["Ahora la dirección a la que estoy mirando","chinx/12","chinx:oRight=true"],
     ["Miro a la izquierda","chinx/35","chinx:oRight=false"],
     ["Luego d la derecha","chinx/35","chinx:oRight=true"],
     ["Izquierda","chinx/36",""],
     ["Derecha","chinx/36",""],
     ["Izquierda","chinx/36",""],
     ["Derecha","chinx/36",""],
     ["Izquierda","chinx/36",""],
     ["Derecha","chinx/36",""],
     // BAILE BIEN PERRON
     ["","chinx/37","chinx:oRight=false;control:paget=50"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     ["","chinx/37","chinx:oRight=false"],
     ["","chinx/37","chinx:oRight=true"],
     //  FIN DEL BAILE BIEN PERRON
     ["Ahora la siguiente prueba","chinx/5","control:paget=800"],
     ["La de voz","chinx/12",""],
     ["realmente es un audio recortado de un grito","chinx/17",""],
     ["para que suene con cada letra que se escribe","chinx/14",""],
     ["Escucha","chinx/12",""],
     ["","chinx/38",""],
     ["Quieres pasar un mal rato?","chinx/39",""],
     ["mhhj!","chinx/40",""],
     ["Que al raton nos vemos","chinx/16",""],
     ["Debe ser el último","chinx/5",""],
     ["ahhh!! Casi lo olvido!","chinx/41",""],
     ["la transparencia tambien","chinx/5",""],
     ["No me debes ver con un fondo blanco siempre","chinx/13",""],
     ["veamos que pasa si nos cambiamos a formato PNG","chinx/16",""],

     ["","chinx/42",""],
     ["","chinx/43",""],
     ["!","chinx/44",""],
     ["Pero solo lo de afuera","chinx/45",""],
     ["","chinx/46",""],
     ["","chinx/47",""],
     ["Shinx-niestro","chinx/48",""],
     ["deberia agregar más cosa como que salga un cuadro de texto para elegi","chinx/49",""],
     ["tambien hacer que tu debas interactuar para seguir con el diálogo","chinx/50",""],
     ["por ahora todo bien","chinx/49",""],
     ["deberia ser en algún otro lugar que no sea una web","chinx/48",""],
     ["Eso es todo y para terminar","chinx/51",""],
     ["muchas gracias por su ayuda","chinx/52",""],
     ["si opinión y datos de lo que sucediò durante su tiempo aquí es necesaria","chinx/53",""],
     ["nos vemos en la versión final","chinx/54",""],
     ["si es que logra salir","chinx/55",""],
     ["","chinx/0",""]
];
